[scan]
# Maximum size of an individual file in bytes, applies to both regular files and files extracted from archives.
# I really do not recommend setting this higher than your RAM
MAX_FILE_SIZE = 2147483648  #2 GB
# Score threshold at which a file is considered infected. Change if you're getting too much false positives/false negatives
DETECTION_THRESHOLD = 51

[archive]
# Max recursion depth. 5 should be more than enough for most cases
MAX_ARCHIVE_DEPTH = 5
# File count limit. Change if needed
MAX_ARCHIVE_FILES = 5000
# Maximum size of an unpacked archive in bytes. Again, do not recommend setting this higher than your RAM
MAX_ARCHIVE_UNPACKED_SIZE = 2147483648  #2 GB